#!/usr/bin/env bash
# Detect external monitor and generate workspace-to-monitor keybinds
# Outputs to ~/.config/hypr/monitors-workspaces.conf which is sourced by hyprland.conf

CONF_DIR="$HOME/.config/hypr"
CONF_FILE="$CONF_DIR/monitors-workspaces.conf"

# Get laptop and external monitors
LAPTOP=$(hyprctl monitors -j | jq -r '.[] | select(.name | startswith("eDP")) | .name' | head -1)
EXTERNAL=$(hyprctl monitors -j | jq -r '.[] | select(.name | startswith("eDP") | not) | .name' | head -1)

# Create config directory if it doesn't exist
mkdir -p "$CONF_DIR"

# If no laptop monitor found, default to eDP-1
if [ -z "$LAPTOP" ]; then
    LAPTOP="eDP-1"
fi

# Start writing the config file
echo "# Auto-generated by monitor-setup.sh - DO NOT EDIT" > "$CONF_FILE"
echo "# Generated at: $(date)" >> "$CONF_FILE"
echo "" >> "$CONF_FILE"

if [ -n "$EXTERNAL" ]; then
    echo "# External monitor detected: $EXTERNAL" >> "$CONF_FILE"
    echo "# Laptop monitor: $LAPTOP" >> "$CONF_FILE"
    echo "" >> "$CONF_FILE"
    echo "# Send workspace to external monitor (SUPER + ALT + [1-0])" >> "$CONF_FILE"
    for i in $(seq 1 10); do
        echo "bind = \$mainMod ALT, $i, moveworkspacetomonitor, $i $EXTERNAL" >> "$CONF_FILE"
    done
    echo "" >> "$CONF_FILE"
    echo "# Bring workspace back to laptop (SUPER + CTRL + [1-0])" >> "$CONF_FILE"
    for i in $(seq 1 10); do
        echo "bind = \$mainMod CTRL, $i, moveworkspacetomonitor, $i $LAPTOP" >> "$CONF_FILE"
    done
else
    echo "# No external monitor detected" >> "$CONF_FILE"
    echo "# Connect an external monitor and run: bash ~/.config/hypr/scripts/monitor-setup.sh" >> "$CONF_FILE"
fi

# Reload Hyprland to apply changes
hyprctl reload 2>/dev/null
